### ISSUE TITLE
publish new version

### ISSUE THREAD

**Issue by KochiyaOcean** [kcwikizh/poi-plugin-subtitle#20]
poi v9.0.0-beta.3 which has in-webview ipc support is released for 9 days. Its able to publish a newer version that using in-webview ipc and remove warning of plugin conflict.

**Comment by KochiyaOcean** [comment]
The warning is not meaningful and causes misinterpretation, and in-webview ipc is a better solution than method used in latest version.

**Comment by KochiyaOcean** [comment]
Its recommended to revert https://github.com/kcwikizh/poi-plugin-subtitle/commit/d2f9d92840e8ee6907c4dd632f368abc67efc369 and merge https://github.com/kcwikizh/poi-plugin-subtitle/pull/16

**Comment by iteamvep** [comment]
Done.
