### ISSUE TITLE
kcwikizh doesn't support English subtitles?

### ISSUE THREAD

**Issue by Werseter** [kcwikizh/poi-plugin-subtitle#21]
The API doesn't seem to provide english subtitles, at least now. Where did the current version of subtitle database come from? Could possibly another source for subtititle updates be found?

**Comment by iteamvep** [comment]
@Werseter We ran into problems with our backend. We are assessing the difficulty to fix them. Thank you for your comment.

**Comment by Werseter** [comment]
I can see that partially it seems to be back up - the diff works, and the recently patched updater fetched new subs :)

But still in [main detail view](https://acc.kcwiki.org/subtitles/detail) only "zh" and "jp" options are present, but it doesn't seem to influence the poi-plugin-subtitle workings.

**Comment by Werseter** [comment]
Confirmed as fixed quite a while ago, closing.
