### ISSUE TITLE
[询问] 一些关于字幕的事情

### ISSUE THREAD

**Issue by Javran** [kcwikizh/poi-plugin-subtitle#3]
想不到比较能总结内容的issue标题了,抱歉(

首先是告知一下,想把你们的 `subtitles.json` 搬运到 KC3 做中文字幕, 之前在微博上有向 @kcwiki舰娘百科 问过,态度是欢迎搬运.

顺着就找到这个repo,想直接把数据文件转成KC3字幕用的格式,应该会比手动搬方便一点. 我们会尊重舰百的共享协议,在KC3的信息页面做credit.

另外想询问两件事情:

- 季节限定语言的翻译是随着官方服务器维护更新,还是有特殊处理?

- `subtitles.json` 这个文件是直接从舰百数据库获得的吗? 或者说如果我想编辑其中的内容,应该通过编辑舰娘百科上的相应条目,而不是直接PR对吗?

**Comment by grzhan** [comment]
> 季节限定语言的翻译是随着官方服务器维护更新,还是有特殊处理?

季节性数据是在原有字幕数据的上，通过抓取对应词条数据（[http://zh.kcwiki.moe/wiki/%E5%AD%A3%E8%8A%82%E6%80%A7/2016%E5%B9%B4%E6%98%A5%E8%87%B3](http://zh.kcwiki.moe/wiki/%E5%AD%A3%E8%8A%82%E6%80%A7/2016%E5%B9%B4%E6%98%A5%E8%87%B3)）覆盖对应舰娘的【秘书舰1】（也可能是2）部分得到的。

因此在出现新语音的时候，需要舰百的翻译编辑程序们一同协作更新。

> `subtitles.json` 这个文件是直接从舰百数据库获得的吗? 或者说如果我想编辑其中的内容,应该通过编辑舰娘百科上的相应条目,而不是直接PR对吗?

可以从 [http://api.kcwiki.moe/subtitles](http://api.kcwiki.moe/subtitles) 获得最新的完整的版本（目前插件数据的更新逻辑以远端diff为主），如果需要改进字幕，前往舰娘百科编辑即可，或者加入编辑翻译群和编辑翻译联系。

**Comment by Javran** [comment]
感谢解答!

**Comment by Javran** [comment]
@grzhan  问下现在的季节性数据还在 http://api.kcwiki.moe/subtitles 里吗? 似乎这两天并未更新.

**Comment by grzhan** [comment]
@Javran 季节性数据在 http://api.kcwiki.moe/subtitles 里是一直更新的，2016初夏的数据由于是前两天翻译们刚整理出来，而且与语音编号的对应发生了变化，所以还没上传上去。基本上待会就更新。

不包含季节性数据的是`subtitles/detail`接口，详情可以参考[kcwiki-api的文档](https://github.com/kcwikizh/kcwiki-api/wiki/Subtitle)

**Comment by grzhan** [comment]
@Javran 其实是这几天上班赶论文比较忙，导致更新脚本没及时更新，影响到了你们那边，抱歉qwq

**Comment by grzhan** [comment]
此外，如果想要自己抓取字幕，这里有字幕抓取的脚本可供参考（deprecated/update_subtitles.py）：https://github.com/grzhan/kcwiki-scripts

如果需要我之后补上README说下命令操作

**Comment by grzhan** [comment]
@Javran 初夏语音更新完毕

**Comment by Javran** [comment]
@grzhan 哦没事的可以理解,感谢提供支持和更新!

**Comment by Javran** [comment]
@grzhan 话说有空更新一下盛夏的字幕吗? 不会很急,能在12号服务器维护之前更新就好了.
(顺带我自己研究下你上次提到的工具怎么用吧

**Comment by grzhan** [comment]
@Javran 现在是舰娘百科的盛夏语音文件档名出现了问题，我要等那边的模板修复才能更新。

**Comment by Javran** [comment]
@grzhan 唔,知道了,那只能等了..

**Comment by grzhan** [comment]
@Javran 和站长商量了下，这两天我可能会hack下抓取脚本，应该可以更新出来

**Comment by Javran** [comment]
@grzhan 非常感谢! (本来打算自己也写个试试((

**Comment by grzhan** [comment]
@Javran 已经更新了盛夏字幕，但是我看了下百科条目本身台词有缺失还有问题。可以等之后字幕更新，如果发现问题了请到技术群报告。

**Comment by Javran** [comment]
@grzhan 了解,谢谢~
