### ISSUE TITLE
KCwiki Quotes Subtitle Plugin displays shipgirl subtitles in Chinese instead of English

### ISSUE THREAD

**Issue by Kenst1092** [kcwikizh/poi-plugin-subtitle#6]
Directly copy-pasted from an issue I posted on Poi Browser, because I was redirected here from the creators of Poi Browser:

The KCwiki Quotes Subtitle Plugin appears to be in English before downloading the plugin, but after downloading, it changes to a Chinese language, and subsequently, all shipgirl subtitles are displayed in Chinese instead of English. Running the latest Poi browser pre-release. Also tried on latest stable release, still having the same problem.

Before downloading:
![untitled1](https://cloud.githubusercontent.com/assets/20787137/17317807/eeed96d4-58b3-11e6-85be-8f03f54150f9.png)

After downloading:

![untitled](https://cloud.githubusercontent.com/assets/20787137/17317823/0e82679a-58b4-11e6-9e4d-f16322b980e6.png)

**Comment by grzhan** [comment]
Try `poi-plugin-subtitle@0.4.0-beta.4`

English is not supported in stable versions.

0.4.0 is a beta version, so please report to us if you encounter any problems.

**Comment by grzhan** [comment]
Now this plugin supports Traditional Chinese, Simplified Chinese, and Japanese.

**Comment by Kenst1092** [comment]
That's kinda sad. Is that because the amount of English users for Poi is very low?

**Comment by Kenst1092** [comment]
UPDATE: While I do appreciate that you put up a beta, I still do not see an option to have subtitles in **_English_**. All I get is _Japanese_ subtitles, but I am an American player, so I do not know neither Japanese nor Chinese.

**Comment by grzhan** [comment]
I'm sorry to say that English is not supported yet.

After discussion with  @TrickLin (kcwiki webmaster) , we may cooperate with [kancollewiki.net](http://en.kancollewiki.net/), who has translated subtitles from Japanese to English.Therefore we would support English sooner or later.

**Comment by Kenst1092** [comment]
Thank you for addressing the issue, at least I am informed.
